#!/usr/bin/env bash

# Install Nginx
sudo apt update
sudo apt install nginx -y

# Get the hostname
HOSTNAME=$(hostname)

# Configure Nginx to add custom response header
HEADER="\\\n\tadd_header X-Served-By $HOSTNAME;\n"
CONFIG_FILE="/etc/nginx/sites-available/default"
FIND=$(grep "X-Served-By" "$CONFIG_FILE")

# Check if the custom header is already configured
if [[ -z $FIND ]]; then
    # Add custom header configuration to Nginx configuration file
    sed -i "/server_name _;/a $HEADER" "$CONFIG_FILE"
fi

# Restart Nginx to apply changes
# Use the appropriate command based on your init system
# For SysVinit systems (e.g., Debian 9), use:
# sudo service nginx restart
# For Upstart systems (e.g., Ubuntu 14.04), use:
# sudo initctl restart nginx
# For other systems, consult the documentation or use the appropriate command.
# Here, we'll use the generic approach of stopping and starting Nginx.
sudo nginx -t && sudo nginx -s reload

